version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: botcreator_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: botcreator
      MYSQL_USER: botcreator
      MYSQL_PASSWORD: botcreator123
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql:ro
    networks:
      - botcreator_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword123"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Bot Creator Platform Application
  app:
    build: .
    container_name: botcreator_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SECRET_KEY=your-super-secret-production-key-change-this
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=botcreator
      - DB_PASSWORD=botcreator123
      - DB_NAME=botcreator
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
      - ./uploads:/app/uploads
    networks:
      - botcreator_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: botcreator_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/static:ro
    depends_on:
      - app
    networks:
      - botcreator_network
    profiles:
      - production

volumes:
  mariadb_data:
    driver: local

networks:
  botcreator_network:
    driver: bridge